print("-------- Isi Biodata Berikut Ini --------")
nama = input("Masukkan nama Anda: ")
ttl = input("Masukkan TTL Anda: ")
alamat = input("Masukkan Alamat Anda: ")
no_hp = input("Masukkan Nomor HP Anda: ")
prodi = input("Masukkan Program Studi Anda: ")
hobi = input("Masukkan Hobi Anda: ")

print("")
print("")
print("-------- Biodata Diri --------")
print("Nama: ", nama)
print("TTL: ", ttl)
print("Alamat: ", alamat)
print("No. HP: ", no_hp)
print("Program Studi: ", prodi)
print("Hobi: ", hobi)
